config:
  ul-indent: false # MD007
  line-length: false # MD013
  no-duplicate-heading: false # MD024
  reference-links-images: false # MD052
  first-line-heading: false # MD041
  no-bare-urls: false # MD034
