AllCops:
  Exclude:
    - vendor/**/*
    - test/**/*
    - bin/**/*

AlignParameters:
  Enabled: false

LineLength:
  Max: 200

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 170

Metrics/BlockLength:
  Max: 250

CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 9

Style/AsciiComments:
  Enabled: false

Style/FileName:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SignalException:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

RegexpLiteral:
  Enabled: false
