default['grafana']['install_type'] = "git" # git | file
default['grafana']['git']['url'] = "https://github.com/torkelo/grafana"
default['grafana']['git']['branch'] = "master"
default['grafana']['git']['type'] = "sync" # checkout | sync
default['grafana']['file']['type'] = "zip" # zip
default['grafana']['file']['url'] = "https://github.com/torkelo/grafana/releases/download/v1.4.0/grafana-1.4.0.zip"
default['grafana']['file']['checksum'] = "40466d58a257c7daf9f0ef87147356d3f1cfdfcb27c5a97c404a508dd101d9e7" # sha256 ( shasum -a 256 FILENAME )
default['grafana']['webserver'] = "nginx"
default['grafana']['install_path'] = "/opt"
default['grafana']['install_dir'] = "#{node['grafana']['install_path']}/grafana"
default['grafana']['es_server'] = "127.0.0.1"
default['grafana']['es_port'] = "9200"
default['grafana']['es_role'] = "elasticsearch_server"
default['grafana']['es_scheme'] = "http://"
default['grafana']['es_user'] = ''
default['grafana']['es_password'] = ''
default['grafana']['graphite_server'] = "127.0.0.1"
default['grafana']['graphite_port'] = "80"
default['grafana']['graphite_role'] = "graphite_server"
default['grafana']['graphite_scheme'] = "http://"
default['grafana']['graphite_user'] = ''
default['grafana']['graphite_password'] = ''
default['grafana']['user'] = ''
default['grafana']['config_template'] = 'config.js.erb'
default['grafana']['config_cookbook'] = 'grafana'
default['grafana']['webserver_hostname'] = node.name
default['grafana']['webserver_aliases'] = [node.ipaddress]
default['grafana']['webserver_listen'] = node.ipaddress
default['grafana']['webserver_port'] = 80
default['grafana']['webserver_scheme'] = "http://"
